common:
  dist:
    port: '25929'
model:
  architecture: 'Oadtr'
slover:
  lr: 0.0001
  weight_decay: 0.0001
  batch_size: 8
dataset:
  data_root: '/mnt/lustrenew/share/lirunze/data/'
  position: 'all'
  num_workers: 16
training:
  epochs: 60